const Property = require("../models/Property");
const User = require("../models/User");
const router = require("express").Router();

router.post("/addPropertyTemp", async (req, res) => {
  console.log("Request to add store");
 let tmp = [
    {
      "name": "Dolcezza Artisanal Gelato",
      "address": "1704 Connecticut Ave NW",
      "zip": 20009,
      "city": "Washington",
      "state": "DC",
      "type": "Ice Cream",
      "Latitude": 38.912855,
      "Longitude": -77.045645,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1704,
      "Street": "Connecticut Ave NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20009,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Cosi 12th and G",
      "address": "700 11th Street NW",
      "zip": 20001,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.898749,
      "Longitude": -77.027322,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 700,
      "Street": "11th St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20001,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Spring Mill Bread Co.",
      "address": "12187 Darnestown Rd",
      "zip": 20878,
      "city": "Gaithersburg",
      "state": "MD",
      "type": "Bakery",
      "Latitude": 39.118169,
      "Longitude": -77.251699,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 12187,
      "Street": "Darnestown Rd",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Gaithersburg",
      "State": "MD",
      "County": "Montgomery County",
      "Zip": 20878,
      "Country": "US",
      "Source": "Montgomery"
    },
    {
      "name": "Cosi Charles St",
      "address": "100 S Charles Street",
      "zip": 21201,
      "city": "Baltimore",
      "state": "MD",
      "type": "Bakery",
      "Latitude": 39.287184,
      "Longitude": -76.615606,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 100,
      "Street": "S Charles St",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Baltimore",
      "State": "MD",
      "County": "Baltimore city",
      "Zip": 21201,
      "Country": "US",
      "Source": "City of Baltimore"
    },
    {
      "name": "Dolcezza Artisanal Gelato",
      "address": "7111 Bethesda Lane",
      "zip": 20814,
      "city": "Bethesda",
      "state": "MD",
      "type": "Ice Cream",
      "Latitude": 38.981169,
      "Longitude": -77.097618,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 7111,
      "Street": "Bethesda Ln",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Bethesda",
      "State": "MD",
      "County": "Montgomery County",
      "Zip": 20814,
      "Country": "US",
      "Source": "Montgomery"
    },
    {
      "name": "Quartermaine Coffee Roasters",
      "address": "4817 Bethesda Ave",
      "zip": 20814,
      "city": "Bethesda",
      "state": "MD",
      "type": "Coffee Shop",
      "Latitude": 38.981067,
      "Longitude": -77.096506,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 4817,
      "Street": "Bethesda Ave",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Bethesda",
      "State": "MD",
      "County": "Montgomery County",
      "Zip": 20814,
      "Country": "US",
      "Source": "Montgomery"
    },
    {
      "name": "Chinatown Coffee Co.",
      "address": "475 H St NW",
      "zip": 20001,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.900078,
      "Longitude": -77.018645,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 475,
      "Street": "H St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20001,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "CakeLove",
      "address": "4150 Campbell Ave.",
      "zip": "Suite 105",
      "city": 22206,
      "state": "Shirlington",
      "type": "VA",
      "Latitude": "Bakery",
      "Longitude": 38.840766,
      "Accuracy Score": -77.089713,
      "Accuracy Type": 1,
      "Number": "rooftop",
      "Street": 4150,
      "Unit Type": "Campbell Ave",
      "Unit Number": "Ste",
      "City": 105,
      "State": "Arlington",
      "County": "VA",
      "Zip": "Arlington County",
      "Country": 22206,
      "Source": "US"
    },
    {
      "name": "Frosting Cupcakery",
      "address": "1 Wisconsin Circle Drive",
      "zip": 20815,
      "city": "Chevy Chase",
      "state": "MD",
      "type": "Coffee Shop",
      "Latitude": 38.961889,
      "Longitude": -77.084684,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1,
      "Street": "Wisconsin Cir",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Chevy Chase",
      "State": "MD",
      "County": "Montgomery County",
      "Zip": 20815,
      "Country": "US",
      "Source": "Montgomery"
    },
    {
      "name": "Cosi Courthouse",
      "address": "2050 Wilson Blvd",
      "zip": 22209,
      "city": "Arlington",
      "state": "VA",
      "type": "Bakery",
      "Latitude": 38.891321,
      "Longitude": -77.084599,
      "Accuracy Score": 0.95,
      "Accuracy Type": "rooftop",
      "Number": 2050,
      "Street": "Wilson Blvd",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Arlington",
      "State": "VA",
      "County": "Arlington County",
      "Zip": 22201,
      "Country": "US",
      "Source": "Arlington"
    },
    {
      "name": "Blind Dog Cafe",
      "address": "944 Florida Avenue NW",
      "zip": 20001,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.919322,
      "Longitude": -77.025182,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 944,
      "Street": "Florida Ave NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20001,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Sidamo Coffee and Tea",
      "address": "8180 Maple Lawn Blvd",
      "zip": 20759,
      "city": "Fulton",
      "state": "MD",
      "type": "Coffee Shop",
      "Latitude": 39.148245,
      "Longitude": -76.906791,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 8180,
      "Street": "Maple Lawn Blvd",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Fulton",
      "State": "MD",
      "County": "Howard County",
      "Zip": 20759,
      "Country": "US",
      "Source": "Howard"
    },
    {
      "name": "Grape + Bean",
      "address": "2 East Walnut St",
      "zip": 22301,
      "city": "Alexandria",
      "state": "VA",
      "type": "Coffee Shop",
      "Latitude": 38.812301,
      "Longitude": -77.061357,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 2,
      "Street": "E Walnut St",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Alexandria",
      "State": "VA",
      "County": "Alexandria city",
      "Zip": 22301,
      "Country": "US",
      "Source": "City of Alexandria"
    },
    {
      "name": "Cosi 601 Penn",
      "address": "601 Penn Ave. NW",
      "zip": 20004,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.894888,
      "Longitude": -77.028635,
      "Accuracy Score": 0.33,
      "Accuracy Type": "place",
      "Number": "",
      "Street": "",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20004,
      "Country": "US",
      "Source": "TIGER/Line® dataset from the US Census Bureau"
    },
    {
      "name": "The B Spot",
      "address": "1123 Pennsylvania Ave SE",
      "zip": 20003,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.882097,
      "Longitude": -76.990714,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1123,
      "Street": "Pennsylvania Ave SE",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20003,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "La Mano Coffee Bar",
      "address": "304 Carroll St NW",
      "zip": 20012,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.974936,
      "Longitude": -77.01653,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 304,
      "Street": "Carroll St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20012,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Cosi Rosslyn",
      "address": "1801 N. Lynn Street",
      "zip": 22209,
      "city": "Arlington",
      "state": "VA",
      "type": "Bakery",
      "Latitude": 38.896713,
      "Longitude": -77.070504,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1801,
      "Street": "N Lynn St",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Arlington",
      "State": "VA",
      "County": "Arlington County",
      "Zip": 22209,
      "Country": "US",
      "Source": "Arlington"
    },
    {
      "name": "Buzz Bakery",
      "address": "901 Slaters Lane",
      "zip": 22314,
      "city": "Alexandria",
      "state": "VA",
      "type": "Bakery",
      "Latitude": 38.821579,
      "Longitude": -77.047627,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 901,
      "Street": "Slaters Ln",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Alexandria",
      "State": "VA",
      "County": "Alexandria city",
      "Zip": 22314,
      "Country": "US",
      "Source": "City of Alexandria"
    },
    {
      "name": "Ebenezers Coffeehouse",
      "address": "201 F Street NE",
      "zip": 20002,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.897139,
      "Longitude": -77.003286,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 201,
      "Street": "F St NE",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20002,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Quartermaine Coffee Roasters",
      "address": "10400 Old Georgetown Road",
      "zip": 20814,
      "city": "Bethesda",
      "state": "MD",
      "type": "Coffee Shop",
      "Latitude": 39.025168,
      "Longitude": -77.126806,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 10400,
      "Street": "Old Georgetown Rd",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Bethesda",
      "State": "MD",
      "County": "Montgomery County",
      "Zip": 20814,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Pitango Gelato",
      "address": "413 7th Street",
      "zip": "NW",
      "city": 20004,
      "state": "Washington",
      "type": "DC",
      "Latitude": "Ice Cream",
      "Longitude": 38.895214,
      "Accuracy Score": -77.021665,
      "Accuracy Type": 1,
      "Number": "rooftop",
      "Street": 413,
      "Unit Type": "7th St NW",
      "Unit Number": "",
      "City": "",
      "State": "Washington",
      "County": "DC",
      "Zip": "District of Columbia",
      "Country": 20004,
      "Source": "US"
    },
    {
      "name": "Pavilion Café at the Sculpture Garden",
      "address": "700 Constitution Avenue NW",
      "zip": 20565,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.892228,
      "Longitude": -77.0219,
      "Accuracy Score": 0.9,
      "Accuracy Type": "range_interpolation",
      "Number": 700,
      "Street": "Constitution Ave NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20004,
      "Country": "US",
      "Source": "TIGER/Line® dataset from the US Census Bureau"
    },
    {
      "name": "Cosi 1333 H St",
      "address": "1333 H St NW",
      "zip": 20005,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.900505,
      "Longitude": -77.031122,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1333,
      "Street": "H St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20005,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Cosi 10th and E",
      "address": "1001 Pennsylvania Ave. NW",
      "zip": 20004,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.895054,
      "Longitude": -77.026508,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1001,
      "Street": "Pennsylvania Ave NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20004,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "St. Elmo's Coffee Pub",
      "address": "2300 Mount Vernon Ave",
      "zip": 22301,
      "city": "Arlington",
      "state": "VA",
      "type": "Coffee Shop",
      "Latitude": 38.826279,
      "Longitude": -77.059097,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 2300,
      "Street": "Mt Vernon Ave",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Alexandria",
      "State": "VA",
      "County": "Alexandria city",
      "Zip": 22301,
      "Country": "US",
      "Source": "City of Alexandria"
    },
    {
      "name": "Pitango Gelato",
      "address": "802 South Broadway",
      "zip": 21231,
      "city": "Baltimore",
      "state": "MD",
      "type": "Ice Cream",
      "Latitude": 39.282385,
      "Longitude": -76.593739,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 802,
      "Street": "S Broadway",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Baltimore",
      "State": "MD",
      "County": "Baltimore city",
      "Zip": 21231,
      "Country": "US",
      "Source": "City of Baltimore"
    },
    {
      "name": "Kramerbooks & Afterwords Cafe",
      "address": "1517 Connecticut Ave NW",
      "zip": 20036,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.910825,
      "Longitude": -77.043818,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1517,
      "Street": "Connecticut Ave NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20036,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Spring Mill Bread Co.",
      "address": "701 8th St SE",
      "zip": 20003,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.881115,
      "Longitude": -76.995245,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 701,
      "Street": "8th St SE",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20003,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Northside Social Coffee & Wine",
      "address": "3211 Wilson Blvd",
      "zip": 22201,
      "city": "Arlington",
      "state": "VA",
      "type": "Coffee Shop",
      "Latitude": 38.885457,
      "Longitude": -77.097794,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 3211,
      "Street": "Wilson Blvd",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Arlington",
      "State": "VA",
      "County": "Arlington County",
      "Zip": 22201,
      "Country": "US",
      "Source": "Arlington"
    },
    {
      "name": "Dolcezza Artisanal Gelato",
      "address": "2905 District Ave",
      "zip": 22031,
      "city": "Fairfax",
      "state": "VA",
      "type": "Ice Cream",
      "Latitude": 38.87253,
      "Longitude": -77.228714,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 2905,
      "Street": "District Ave",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Fairfax",
      "State": "VA",
      "County": "Fairfax County",
      "Zip": 22031,
      "Country": "US",
      "Source": "Fairfax"
    },
    {
      "name": "Tryst at the Phillips Collection",
      "address": "1600 21st Street",
      "zip": "NW",
      "city": 20009,
      "state": "Washington",
      "type": "DC",
      "Latitude": "Coffee Shop",
      "Longitude": 38.91151,
      "Accuracy Score": -77.046855,
      "Accuracy Type": 1,
      "Number": "rooftop",
      "Street": 1600,
      "Unit Type": "21st St NW",
      "Unit Number": "",
      "City": "",
      "State": "Washington",
      "County": "DC",
      "Zip": "District of Columbia",
      "Country": 20009,
      "Source": "US"
    },
    {
      "name": "Pitango Gelato",
      "address": "1451 P Street",
      "zip": "NW",
      "city": 20005,
      "state": "Washington",
      "type": "DC",
      "Latitude": "Ice Cream",
      "Longitude": 38.909828,
      "Accuracy Score": -77.033856,
      "Accuracy Type": 1,
      "Number": "rooftop",
      "Street": 1451,
      "Unit Type": "P St NW",
      "Unit Number": "",
      "City": "",
      "State": "Washington",
      "County": "DC",
      "Zip": "District of Columbia",
      "Country": 20005,
      "Source": "US"
    },
    {
      "name": "Heller's Bakery",
      "address": "3221 Mount Pleasant St NW",
      "zip": 20010,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.931852,
      "Longitude": -77.038319,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 3221,
      "Street": "Mt Pleasant St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20010,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Bourbon Coffee",
      "address": "2101 L Street NW",
      "zip": 20037,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.904011,
      "Longitude": -77.046882,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 2101,
      "Street": "L St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20037,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Soho Tea and Coffee",
      "address": "2150 P St NW",
      "zip": 20037,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.90948,
      "Longitude": -77.048527,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 2150,
      "Street": "P St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20037,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Cosi Columbia",
      "address": "6181 Old Dobbin Lane Suite 200",
      "zip": 21045,
      "city": "Columbia",
      "state": "MD",
      "type": "Bakery",
      "Latitude": 39.200481,
      "Longitude": -76.811895,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 6181,
      "Street": "Old Dobbin Ln",
      "Unit Type": "Ste",
      "Unit Number": 200,
      "City": "Columbia",
      "State": "MD",
      "County": "Howard County",
      "Zip": 21045,
      "Country": "US",
      "Source": "Howard"
    },
    {
      "name": "Cosi Owings Mills",
      "address": "9177 Reisterstown Road",
      "zip": 21117,
      "city": "Owings Mills",
      "state": "MD",
      "type": "Bakery",
      "Latitude": 39.397408,
      "Longitude": -76.7484,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 9177,
      "Street": "Reisterstown Rd",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Owings Mills",
      "State": "MD",
      "County": "Baltimore County",
      "Zip": 21117,
      "Country": "US",
      "Source": "Baltimore"
    },
    {
      "name": "Big Bear Cafe",
      "address": "1700 1st St NW",
      "zip": 20001,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.912763,
      "Longitude": -77.012367,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1700,
      "Street": "1st St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20001,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "M.E. Swing Coffeehouse",
      "address": "1702 G Street NW",
      "zip": 20006,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.89816,
      "Longitude": -77.039982,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1702,
      "Street": "G St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20006,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Dangerously Delicious Pies",
      "address": "1339 H Street NE",
      "zip": 20002,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.899926,
      "Longitude": -76.986925,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1339,
      "Street": "H St NE",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20002,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Baked & Wired",
      "address": "1052 Thomas Jefferson Street NW",
      "zip": 20007,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.903887,
      "Longitude": -77.060437,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1052,
      "Street": "Thomas Jefferson St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20007,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Flying Fish Coffee and Tea",
      "address": "3064 Mount Pleasant St NW",
      "zip": 20009,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.92846,
      "Longitude": -77.037509,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 3064,
      "Street": "Mt Pleasant St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20009,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Cosi Chevy Chase",
      "address": "5252 Wisconsin Ave NW",
      "zip": 20015,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.958745,
      "Longitude": -77.085149,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 5252,
      "Street": "Wisconsin Ave NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20015,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Dangerously Delicious Pies",
      "address": "50 Massachusetts Ave NE",
      "zip": 20002,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.897546,
      "Longitude": -77.006181,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 50,
      "Street": "Massachusetts Ave NE",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20002,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Peregrine Espresso",
      "address": "1309 5th St NE",
      "zip": 20002,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.908724,
      "Longitude": -76.997653,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1309,
      "Street": "5th St NE",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20002,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Cosi DuPont North",
      "address": "1647 20th St. NW",
      "zip": 20009,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.912479,
      "Longitude": -77.044572,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1647,
      "Street": "20th St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20009,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Cosi Alexandria",
      "address": "700 King Street",
      "zip": 22314,
      "city": "Alexandria",
      "state": "VA",
      "type": "Bakery",
      "Latitude": 38.804985,
      "Longitude": -77.047194,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 700,
      "Street": "King St",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Alexandria",
      "State": "VA",
      "County": "Alexandria city",
      "Zip": 22314,
      "Country": "US",
      "Source": "City of Alexandria"
    },
    {
      "name": "Cosi Bethesda",
      "address": "7251 Woodmont Avenue",
      "zip": 20814,
      "city": "Bethesda",
      "state": "MD",
      "type": "Bakery",
      "Latitude": 38.981626,
      "Longitude": -77.095657,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 7251,
      "Street": "Woodmont Ave",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Bethesda",
      "State": "MD",
      "County": "Montgomery County",
      "Zip": 20814,
      "Country": "US",
      "Source": "Montgomery"
    },
    {
      "name": "Cosi Ballston",
      "address": "4250 Fairfax Drive",
      "zip": 22203,
      "city": "Arlington",
      "state": "VA",
      "type": "Bakery",
      "Latitude": 38.881885,
      "Longitude": -77.112216,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 4250,
      "Street": "Fairfax Dr",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Arlington",
      "State": "VA",
      "County": "Arlington County",
      "Zip": 22203,
      "Country": "US",
      "Source": "Arlington"
    },
    {
      "name": "Cosi 1700 Penn",
      "address": "1700 Pennsylvania Ave",
      "zip": 20006,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.898657,
      "Longitude": -77.039958,
      "Accuracy Score": 0.9,
      "Accuracy Type": "rooftop",
      "Number": 1700,
      "Street": "Pennsylvania Ave NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20006,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Tryst",
      "address": "2473 18th St NW",
      "zip": 20009,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.922335,
      "Longitude": -77.042275,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 2473,
      "Street": "18th St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20009,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Sidamo Coffee & Tea",
      "address": "417 H St NE",
      "zip": 20002,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.900022,
      "Longitude": -76.99991,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 417,
      "Street": "H St NE",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20002,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Caffe Amouri",
      "address": "107 Church St NE",
      "zip": 22180,
      "city": "Vienna",
      "state": "VA",
      "type": "Bakery",
      "Latitude": 38.902565,
      "Longitude": -77.265693,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 107,
      "Street": "Church St NE",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Vienna",
      "State": "VA",
      "County": "Fairfax County",
      "Zip": 22180,
      "Country": "US",
      "Source": "Fairfax"
    },
    {
      "name": "Sticky Fingers Bakery",
      "address": "1370 Park Rd NW",
      "zip": 20010,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.930477,
      "Longitude": -77.03174,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1370,
      "Street": "Park Rd NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20010,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Filter Coffeehouse & Espresso Bar",
      "address": "1726 20th Street",
      "zip": "NW",
      "city": 20009,
      "state": "Washington",
      "type": "DC",
      "Latitude": "Coffee Shop",
      "Longitude": 38.913694,
      "Accuracy Score": -77.045095,
      "Accuracy Type": 1,
      "Number": "rooftop",
      "Street": 1726,
      "Unit Type": "20th St NW",
      "Unit Number": "",
      "City": "",
      "State": "Washington",
      "County": "DC",
      "Zip": "District of Columbia",
      "Country": 20009,
      "Source": "US"
    },
    {
      "name": "Lot 38 Espresso Bar",
      "address": "1001 2nd St SE",
      "zip": 20003,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.877737,
      "Longitude": -77.003695,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1001,
      "Street": "2nd St SE",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20003,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "KoGiBow Bakery",
      "address": "1817 Adams Mill Rd NW",
      "zip": 20009,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.923314,
      "Longitude": -77.042654,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1817,
      "Street": "Adams Mill Rd NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20009,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Cosi Falls Church",
      "address": "513 W Broad Street",
      "zip": 22046,
      "city": "Falls Church",
      "state": "VA",
      "type": "Bakery",
      "Latitude": 38.886675,
      "Longitude": -77.178416,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 513,
      "Street": "W Broad St",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Falls Church",
      "State": "VA",
      "County": "Falls Church city",
      "Zip": 22046,
      "Country": "US",
      "Source": "City of Falls Church"
    },
    {
      "name": "Grape + Bean",
      "address": "118 South Royal St",
      "zip": 22314,
      "city": "Alexandria",
      "state": "VA",
      "type": "Coffee Shop",
      "Latitude": 38.803944,
      "Longitude": -77.04363,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 118,
      "Street": "S Royal St",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Alexandria",
      "State": "VA",
      "County": "Alexandria city",
      "Zip": 22314,
      "Country": "US",
      "Source": "City of Alexandria"
    },
    {
      "name": "Filter Coffeehouse & Espresso Bar",
      "address": "1916 I Street",
      "zip": "NW",
      "city": 20006,
      "state": "Washington",
      "type": "DC",
      "Latitude": "Coffee Shop",
      "Longitude": 38.90115,
      "Accuracy Score": -77.044172,
      "Accuracy Type": 1,
      "Number": "rooftop",
      "Street": 1916,
      "Unit Type": "I St NW",
      "Unit Number": "",
      "City": "",
      "State": "Washington",
      "County": "DC",
      "Zip": "District of Columbia",
      "Country": 20006,
      "Source": "US"
    },
    {
      "name": "CakeLove",
      "address": "1506 U St NW",
      "zip": 20009,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.916862,
      "Longitude": -77.034968,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1506,
      "Street": "U St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20009,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Dolcezza Artisanal Gelato",
      "address": "1560 Wisconsin Ave NW",
      "zip": 20007,
      "city": "Washington",
      "state": "DC",
      "type": "Ice Cream",
      "Latitude": 38.910338,
      "Longitude": -77.065021,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1560,
      "Street": "Wisconsin Ave NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20007,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Ceremony Coffee Roasters",
      "address": "90 Russell St",
      "zip": 21401,
      "city": "Annapolis",
      "state": "MD",
      "type": "Coffee Shop",
      "Latitude": 38.976282,
      "Longitude": -76.512386,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 90,
      "Street": "Russell St",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Annapolis",
      "State": "MD",
      "County": "Anne Arundel County",
      "Zip": 21401,
      "Country": "US",
      "Source": "Anne Arundel"
    },
    {
      "name": "Buzz Bakery",
      "address": "818 N. Quincy Street",
      "zip": 22217,
      "city": "Arlington",
      "state": "VA",
      "type": "Bakery",
      "Latitude": 38.880339,
      "Longitude": -77.107848,
      "Accuracy Score": 0.9,
      "Accuracy Type": "rooftop",
      "Number": 818,
      "Street": "N Quincy St",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Arlington",
      "State": "VA",
      "County": "Arlington County",
      "Zip": 22203,
      "Country": "US",
      "Source": "Arlington"
    },
    {
      "name": "CakeLove",
      "address": "160 National Plaza",
      "zip": 20745,
      "city": "Oxon",
      "state": "MD",
      "type": "Bakery",
      "Latitude": 38.78445,
      "Longitude": -77.016898,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 160,
      "Street": "National Plz",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Oxon Hill",
      "State": "MD",
      "County": "Prince George's County",
      "Zip": 20745,
      "Country": "US",
      "Source": "Prince Georges"
    },
    {
      "name": "Cosi Rockville",
      "address": "201 N. Washington Street #290",
      "zip": 20850,
      "city": "Rockville",
      "state": "MD",
      "type": "Bakery",
      "Latitude": 39.085266,
      "Longitude": -77.152697,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 201,
      "Street": "N Washington St",
      "Unit Type": "#",
      "Unit Number": 290,
      "City": "Rockville",
      "State": "MD",
      "County": "Montgomery County",
      "Zip": 20850,
      "Country": "US",
      "Source": "City of Rockville"
    },
    {
      "name": "Pound the Hill (Cafe)",
      "address": "621 Pennsylvania Ave SE",
      "zip": 20003,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.884906,
      "Longitude": -76.997682,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 621,
      "Street": "Pennsylvania Ave SE",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20003,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "CakeLove",
      "address": "8512 Fenton Street",
      "zip": 20910,
      "city": "Silver Spring",
      "state": "MD",
      "type": "Bakery",
      "Latitude": 38.996276,
      "Longitude": -77.025052,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 8512,
      "Street": "Fenton St",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Silver Spring",
      "State": "MD",
      "County": "Montgomery County",
      "Zip": 20910,
      "Country": "US",
      "Source": "Montgomery"
    },
    {
      "name": "Cosi Reston",
      "address": "11909 Democracy Drive",
      "zip": 20190,
      "city": "Reston",
      "state": "VA",
      "type": "Bakery",
      "Latitude": 38.957699,
      "Longitude": -77.357941,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 11909,
      "Street": "Democracy Dr",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Reston",
      "State": "VA",
      "County": "Fairfax County",
      "Zip": 20190,
      "Country": "US",
      "Source": "Fairfax"
    },
    {
      "name": "Bread & Brew",
      "address": "1247 20th St",
      "zip": "NW",
      "city": 20036,
      "state": "Washington",
      "type": "DC",
      "Latitude": "Bakery",
      "Longitude": 38.906981,
      "Accuracy Score": -77.044642,
      "Accuracy Type": 1,
      "Number": "rooftop",
      "Street": 1247,
      "Unit Type": "20th St NW",
      "Unit Number": "",
      "City": "",
      "State": "Washington",
      "County": "DC",
      "Zip": "District of Columbia",
      "Country": 20036,
      "Source": "US"
    },
    {
      "name": "Dangerously Delicious Pies",
      "address": "675 I St. NW",
      "zip": 20005,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.901034,
      "Longitude": -77.021449,
      "Accuracy Score": 0.95,
      "Accuracy Type": "rooftop",
      "Number": 675,
      "Street": "I St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20001,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Politics & Prose",
      "address": "5015 Connecticut Ave NW",
      "zip": 20008,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.955473,
      "Longitude": -77.069648,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 5015,
      "Street": "Connecticut Ave NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20008,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Cosi Crystal Drive",
      "address": "2011 Crystal Drive Suite 100",
      "zip": 22202,
      "city": "Arlington",
      "state": "VA",
      "type": "Bakery",
      "Latitude": 38.855557,
      "Longitude": -77.048619,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 2011,
      "Street": "Crystal Dr",
      "Unit Type": "Ste",
      "Unit Number": 100,
      "City": "Arlington",
      "State": "VA",
      "County": "Arlington County",
      "Zip": 22202,
      "Country": "US",
      "Source": "Arlington"
    },
    {
      "name": "Cosi FDIC",
      "address": "3503 Fairfax Drive Suite 200",
      "zip": 22226,
      "city": "Arlington",
      "state": "VA",
      "type": "Bakery",
      "Latitude": 38.883991,
      "Longitude": -77.10322,
      "Accuracy Score": 0.9,
      "Accuracy Type": "rooftop",
      "Number": 3503,
      "Street": "Fairfax Dr",
      "Unit Type": "Ste",
      "Unit Number": 200,
      "City": "Arlington",
      "State": "VA",
      "County": "Arlington County",
      "Zip": 22201,
      "Country": "US",
      "Source": "Arlington"
    },
    {
      "name": "BeanGood Coffee Pub",
      "address": "1737 Wilson Blvd",
      "zip": 22209,
      "city": "Arlington",
      "state": "VA",
      "type": "Coffee Shop",
      "Latitude": 38.894063,
      "Longitude": -77.079191,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1737,
      "Street": "Wilson Blvd",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Arlington",
      "State": "VA",
      "County": "Arlington County",
      "Zip": 22209,
      "Country": "US",
      "Source": "Arlington"
    },
    {
      "name": "Peregrine Espresso",
      "address": "660 Pennsylvania Ave SE",
      "zip": 20003,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.885172,
      "Longitude": -76.996565,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 660,
      "Street": "Pennsylvania Ave SE",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20003,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Cosi Gaithersburg",
      "address": "177 Kentlands Blvd",
      "zip": 20878,
      "city": "Gaithersburg",
      "state": "MD",
      "type": "Bakery",
      "Latitude": 39.123393,
      "Longitude": -77.234347,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 177,
      "Street": "Kentlands Blvd",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Gaithersburg",
      "State": "MD",
      "County": "Montgomery County",
      "Zip": 20878,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Buzz Bakery",
      "address": "300 Tingey St",
      "zip": "SE",
      "city": 20003,
      "state": "Washington",
      "type": "DC",
      "Latitude": "Bakery",
      "Longitude": 38.875225,
      "Accuracy Score": -77.001275,
      "Accuracy Type": 1,
      "Number": "rooftop",
      "Street": 300,
      "Unit Type": "Tingey St SE",
      "Unit Number": "",
      "City": "",
      "State": "Washington",
      "County": "DC",
      "Zip": "District of Columbia",
      "Country": 20003,
      "Source": "US"
    },
    {
      "name": "Qualia Coffee",
      "address": "3917 Georgia Ave NW",
      "zip": 20011,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.939193,
      "Longitude": -77.024516,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 3917,
      "Street": "Georgia Ave NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20011,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Open City",
      "address": "2331 Calvert St. NW",
      "zip": 20008,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.923725,
      "Longitude": -77.052368,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 2331,
      "Street": "Calvert St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20008,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Cosi DuPont South",
      "address": "1350 Connecticut Ave.",
      "zip": 20036,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.908313,
      "Longitude": -77.043082,
      "Accuracy Score": 0.9,
      "Accuracy Type": "rooftop",
      "Number": 1350,
      "Street": "Connecticut Ave NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20036,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Peregrine Espresso",
      "address": "1718 14th St NW",
      "zip": 20009,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.913274,
      "Longitude": -77.032266,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1718,
      "Street": "14th St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20009,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Pitango Gelato",
      "address": "11942 Democracy Drive",
      "zip": 20190,
      "city": "Reston",
      "state": "VA",
      "type": "Ice Cream",
      "Latitude": 38.958037,
      "Longitude": -77.358169,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 11942,
      "Street": "Democracy Dr",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Reston",
      "State": "VA",
      "County": "Fairfax County",
      "Zip": 20190,
      "Country": "US",
      "Source": "Fairfax"
    },
    {
      "name": "Misha's Coffeehouse and Roaster",
      "address": "102 S Patrick St",
      "zip": 22314,
      "city": "Alexandria",
      "state": "VA",
      "type": "Coffee Shop",
      "Latitude": 38.805229,
      "Longitude": -77.050209,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 102,
      "Street": "S Patrick St",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Alexandria",
      "State": "VA",
      "County": "Alexandria city",
      "Zip": 22314,
      "Country": "US",
      "Source": "City of Alexandria"
    },
    {
      "name": "U Street Cafe",
      "address": "1301 U St NW",
      "zip": 20009,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.917294,
      "Longitude": -77.03052,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1301,
      "Street": "U St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20009,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Courtyard Café at the National Portrait Gallery",
      "address": "800 F St NW",
      "zip": 20001,
      "city": "Washington",
      "state": "DC",
      "type": "Coffee Shop",
      "Latitude": 38.896987,
      "Longitude": -77.023286,
      "Accuracy Score": 0.95,
      "Accuracy Type": "rooftop",
      "Number": 800,
      "Street": "F St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20004,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Patisserie Poupon",
      "address": "820 East Baltimore Street",
      "zip": 21202,
      "city": "Baltimore",
      "state": "MD",
      "type": "Bakery",
      "Latitude": 39.290427,
      "Longitude": -76.60485,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 820,
      "Street": "E Baltimore St",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Baltimore",
      "State": "MD",
      "County": "Baltimore city",
      "Zip": 21202,
      "Country": "US",
      "Source": "City of Baltimore"
    },
    {
      "name": "Cosi 15th and K",
      "address": "1501 K Street NW",
      "zip": 20005,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.90296,
      "Longitude": -77.035121,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1501,
      "Street": "K St NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20005,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Patisserie Poupon",
      "address": "1645 Wisconsin Avenue NW",
      "zip": 20007,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.911626,
      "Longitude": -77.065281,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 1645,
      "Street": "Wisconsin Ave NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20007,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Spring Mill Bread Co.",
      "address": "4961 Elm Street",
      "zip": 20814,
      "city": "Bethesda",
      "state": "MD",
      "type": "Bakery",
      "Latitude": 38.982196,
      "Longitude": -77.098161,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 4961,
      "Street": "Elm St",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Bethesda",
      "State": "MD",
      "County": "Montgomery County",
      "Zip": 20814,
      "Country": "US",
      "Source": "Montgomery"
    },
    {
      "name": "Cosi Capitol Hill",
      "address": "301 Pennsylvania Ave.  SE",
      "zip": 20003,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.886698,
      "Longitude": -77.001865,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 301,
      "Street": "Pennsylvania Ave SE",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20003,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Dangerously Delicious Pies",
      "address": "2839 O'Donnell St.",
      "zip": 21224,
      "city": "Baltimore",
      "state": "MD",
      "type": "Coffee Shop",
      "Latitude": 39.279854,
      "Longitude": -76.575607,
      "Accuracy Score": 0.89,
      "Accuracy Type": "nearest_rooftop_match",
      "Number": 2835,
      "Street": "O'donnell St",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Baltimore",
      "State": "MD",
      "County": "Baltimore city",
      "Zip": 21224,
      "Country": "US",
      "Source": "City of Baltimore"
    },
    {
      "name": "Pitango Gelato",
      "address": "660 Pennsylvania Ave. SE",
      "zip": 20003,
      "city": "Washington",
      "state": "DC",
      "type": "Ice Cream",
      "Latitude": 38.885172,
      "Longitude": -76.996565,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 660,
      "Street": "Pennsylvania Ave SE",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20003,
      "Country": "US",
      "Source": "Statewide"
    },
    {
      "name": "Extra Perks Coffee Shop and Cafe",
      "address": "822 N. Fairfax Street",
      "zip": 22314,
      "city": "Alexandria",
      "state": "VA",
      "type": "Coffee Shop",
      "Latitude": 38.813327,
      "Longitude": -77.040795,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 822,
      "Street": "N Fairfax St",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Alexandria",
      "State": "VA",
      "County": "Alexandria city",
      "Zip": 22314,
      "Country": "US",
      "Source": "City of Alexandria"
    },
    {
      "name": "Old Town Coffee",
      "address": "Tea & Spice",
      "zip": "215 S Union St",
      "city": 22314,
      "state": "Alexandria",
      "type": "VA",
      "Latitude": "Coffee Shop",
      "Longitude": 38.802503,
      "Accuracy Score": -77.040769,
      "Accuracy Type": 1,
      "Number": "rooftop",
      "Street": 215,
      "Unit Type": "S Union St",
      "Unit Number": "",
      "City": "",
      "State": "Alexandria",
      "County": "VA",
      "Zip": "Alexandria city",
      "Country": 22314,
      "Source": "US"
    },
    {
      "name": "Frederick Coffee Company & Cafe",
      "address": "100 N East St",
      "zip": 21701,
      "city": "Frederick",
      "state": "MD",
      "type": "Coffee Shop",
      "Latitude": 39.415349,
      "Longitude": -77.404923,
      "Accuracy Score": 1,
      "Accuracy Type": "rooftop",
      "Number": 100,
      "Street": "Northeast St",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Frederick",
      "State": "MD",
      "County": "Frederick County",
      "Zip": 21701,
      "Country": "US",
      "Source": "Frederick"
    },
    {
      "name": "Cosi Georgetown University",
      "address": "3800 Reservoir Rd. NW",
      "zip": 20057,
      "city": "Washington",
      "state": "DC",
      "type": "Bakery",
      "Latitude": 38.912022,
      "Longitude": -77.075306,
      "Accuracy Score": 0.9,
      "Accuracy Type": "rooftop",
      "Number": 3800,
      "Street": "Reservoir Rd NW",
      "Unit Type": "",
      "Unit Number": "",
      "City": "Washington",
      "State": "DC",
      "County": "District of Columbia",
      "Zip": 20007,
      "Country": "US",
      "Source": "Statewide"
    }
  ];
  const randomCity = [
    {
      name: "Larke",
      value: 250,
      hourlyIncome: 60,
      location: [35.917807, -79.052262],
    },
    {
      name: "Union",
      value: 250,
      hourlyIncome: 60,
      location: [35.91942, -79.0526],
    },
    {
      name: "Home",
      value: 290,
      hourlyIncome: 65,
      location: [35.793781, -78.808533],
    },
    {
      name: "Cary Academy",
      value: 291,
      hourlyIncome: 85,
      location: [35.81996, -78.76825],
    },
    {
      name: "Downtown Cary",
      value: 363,
      hourlyIncome: 85,
      location: [35.79147, -78.781143],
    },
  ];

   tmp = tmp.map(e =>({
     name: e.name,
     value: Math.random()*10000,
     hourlyIncome: Math.random()*10000,
     location: [e.Latitude, e.Longitude]
   }))

   tmp.map(e => {
     new Property(e).save();
   })
  randomCity.map((e) => {
    new Property(e).save();
  });

  res.send("E");
});

router.post("/propertyByID", async (req, res) => {
  if (!req.body.id) {
    res.json({ error: "No ID specified" });
    return;
  }
  if (!req.body.id.match(/^[0-9a-fA-F]{24}$/)) {
    res.json({ error: "Invalid ID specified" });
    return;
  }

  let target = await Property.findById(req.body.id);
  if (!target) {
    res.json({ error: "No Such Property Found" });
    return;
  }
  res.json({ error: null, body: target });
});

router.post("/nearbyProperties", async (req, res) => {
  //Make sure we have input
  if (!req.body.lat) {
    res.json({ error: "Missing lat" });
    return;
  }

  if (!req.body.lon) {
    res.json({ error: "Missing lon" });
    return;
  }

  if (!req.body.range) {
    //TODO Make sure all of these are numbers
    res.json({ error: "Missing range" });
    return;
  }

  const targetLat = req.body.lat;
  const targetLon = req.body.lon;
  const range = req.body.range;

  let results;
  try {
    results = await Property.find({
      location: {
        $near: {
          $maxDistance: range,
          $geometry: {
            type: "Point",
            coordinates: [targetLat, targetLon],
          },
        },
      },
    });
  } catch (error){
    console.log("Error");
    console.log(error);
    console.log(error.toString());
  }

  res.send(results);
});

router.post("/buy", async (req, res) => {
  // Validate input: user, propertyID, tier
  const user = await User.findOne({ email: req.user.email });

  if (!user) {
    res.json({ error: "No such user" });
    return;
  }

  if (!req.body.propertyId) {
    res.json({ error: "No ID specified" });
    return;
  }
  if (!req.body.propertyId.match(/^[0-9a-fA-F]{24}$/)) {
    res.json({ error: "Invalid ID specified" });
    return;
  }

  let targetProperty = await Property.findById(req.body.propertyId);

  if (!targetProperty) {
    res.json({ error: "No Such Property Found" });
    return;
  }

  if (!req.body.tier) {
    res.json({ error: "No tier given" });
    return;
  }

  // Make sure tier is available
  const t = req.body.tier;
  if (t == 1) {
    if (targetProperty.ownerEmailT1 !== "") {
      res.json({ error: "Tier already owned" });
      return;
    }
  } else if (t == 2) {
    if (targetProperty.ownerEmailT2 !== "") {
      res.json({ error: "Tier already owned" });
      return;
    }
  } else if (t == 3) {
    if (targetProperty.ownerEmailT3 !== "") {
      res.json({ error: "Tier already owned" });
      return;
    }
  } else if (t == 4) {
    if (targetProperty.ownerEmailT4 !== "") {
      res.json({ error: "Tier already owned" });
      return;
    }
  } else {
    if (targetProperty.ownerEmailT5 !== "") {
      res.json({ error: "Tier already owned" });
      return;
    }
  }

  // Make sure user has balance
  const price = targetProperty.value ** t;
  if (price > user.balance) {
    res.json({
      error: `Insufficient Funds. Need ${price} but only have ${user.balance}`,
    });
    return;
  }

  // Make sure user has property space
  if ((user.properties.length == user.maxProperties) && !user.properties.contains(req.body.id)) {
    res.json({ error: "Not enough property space" });
    return;
  }

  // Charge user
  user.balance -= price;

  // Update property owners
  if (t == 1) {
    targetProperty.ownerEmailT1 = user.email;
  } else if (t == 2) {
    targetProperty.ownerEmailT2 = user.email;
  } else if (t == 3) {
    targetProperty.ownerEmailT3 = user.email;
  } else if (t == 4) {
    targetProperty.ownerEmailT4 = user.email;
  } else {
    targetProperty.ownerEmailT5 = user.email;
  }

  // Update user properties owned
  if (!user.properties.includes(targetProperty._id)) {
    user.properties.push(targetProperty._id);
  }

  // Save property and user to db
  await user.save(); //TODO shouldn't return password
  await targetProperty.save();

  res.json({
    error: null,
    data: {
      user: user,
      property: targetProperty,
    },
  });
});

module.exports = router;
